### ISSUE TITLE
Daily Bonuses

### ISSUE THREAD

**Issue by CatmanIta** [vgwb/Antura_arabic#491]
Give increasing daily bonuses in the form of N bones or new skins for Antura.
Check that reactivation is handled.

**Comment by CatmanIta** [comment]
Here is the current implementation:
- every time we return to the map, the game checks whether one or more days have passed since last daily reward (this can be changed to trigger at midnight, if needed)
- if exactly 1 day passed, a counter is incremented (ComboPlayDays), starting from zero. 
- the mood scene is shown, followed by the DailyReward scene.
- based on ComboPlayDays, a reward is unlocked

New DailyReward scene features:
- a list of N rewards is shown, one per day, labeled with the day number
- previous rewards are shown unlocked, next rewards are shown locked
- today's reward is highlighted and is unlocked with a button
- when the last day is reached, the scene always gives the maximum reward
- bones counter UI with small animation
- data-driven support for different rewards / different amounts

Issue: this requires that ComboPlayDays is saved with the player profile, but this may break the current saved databases. A migration may be necessary for previous players.

Note that this also changed how the mood scene worked (and fixed the bug that did not allow the mood scene to appear if we left the game running)

**Comment by StefanoCecere** [comment]
@CatmanIta we can save the ComboPlayDays serialized into the AdditionalData.
we shouldn't modify the db scheme if not really really necessary!

**Comment by StefanoCecere** [comment]
done with f5c3464832469aa29d3ea41a04bb3fef5180356c please @CatmanIta  check it!

**Comment by Demigiant** [comment]
https://docs.google.com/presentation/d/1hc5Sjzq6cg_Y-FHgIK819KzfHWOG0KF9jhPh6Klf4Ww/edit#slide=id.g24c0825d9f_0_52

**Comment by Demigiant** [comment]
Made nicer animation for the daily reward + minor graphic adjustments

**Comment by Demigiant** [comment]
Animated daily reward entrance + reworked graphics + click. Bones popping out still missing.

**Comment by Demigiant** [comment]
Bones are now popping out
